apiVersion: v1
kind: Template
metadata:
  name: ${app_name}
objects:
  # Deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${app_name}
    spec:
      replicas: ${{replicas}}
      selector:
        matchLabels:
          app: ${app_name}
      template:
        metadata:
          labels:
            app: ${app_name}
            logFormat: myformat
        spec:
          containers:
            - image: ${image}
              imagePullPolicy: IfNotPresent
              name: ${app_name}
              args:
                - "generate"
                - "--output-format"
                - "json"
                - "--totalLogLines"
                - "${total_log_lines}"
                - "--log-lines-rate"
                - "${log_lines_rate}"

parameters:
  - name: image
    value: "quay.io/openshift-logging/cluster-logging-load-client:latest"
  - name: replicas
    value: "1"
  - name: total_log_lines
    value: "1000"
  - name: log_lines_rate
    value: "1"
  - name: app_name
    value: myapp
