apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
spec:
  logStore:
    type: "elasticsearch"
    retentionPolicy:
      application:
        maxAge: 1m
      infra:
        maxAge: 1m
      audit:
        maxAge: 1m
    elasticsearch:
      nodeCount: 3
      resources:
        requests:
          limits: 2Gi
      redundancyPolicy: "FullRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
