apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
spec:
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 3
      resources:
        requests:
          limits: 2Gi
#        limits:
#          cpu: "1"
#          memory: 2Gi
      redundancyPolicy: "FullRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
  forwarder:
    fluentd:
      buffer:
        chunkLimitSize: 1m
        flushMode: immediate
        flushThreadCount: 32